# Generated by Django 3.0.1 on 2020-04-15 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
