# Generated by Django 3.0.1 on 2020-04-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0007_auto_20200415_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='offer',
        ),
    ]
