# Generated by Django 3.0.1 on 2020-04-21 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('championsDen', '0008_delete_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100, verbose_name='course name')),
                ('course_author', models.CharField(max_length=100, verbose_name='course author')),
                ('role', models.CharField(choices=[('MID', 'MIDLANE'), ('TOP', 'TOPLANE'), ('JUNGLE', 'JUNGLE'), ('BOT', 'BOTLANE'), ('SUPPORT', 'SUPPORT'), ('ALL', 'ALL')], max_length=10)),
                ('tags', models.CharField(max_length=100)),
                ('experience', models.CharField(choices=[('BEGINNER', 'BEGINNER'), ('INTERMEDIATE', 'INTERMEDIATE'), ('EXPERT', 'EXPERT'), ('ALL', 'ALL')], max_length=15)),
                ('category', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('users_with_access_all', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=100, verbose_name='section title')),
                ('video_url', models.CharField(max_length=100)),
                ('section_description', models.TextField(max_length=1000, verbose_name='section description')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='championsDen.Course')),
            ],
        ),
    ]
