# Generated by Django 3.0.1 on 2020-04-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0009_course_course_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users_with_access_all',
            new_name='users_with_access',
        ),
    ]
