# Generated by Django 3.0.1 on 2020-04-21 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0010_auto_20200421_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='category',
            new_name='rank',
        ),
    ]
