# Generated by Django 3.0.1 on 2020-04-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0011_auto_20200421_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_section',
            name='video_url',
            field=models.URLField(max_length=250),
        ),
    ]
