# Generated by Django 3.0.1 on 2020-04-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0014_auto_20200422_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_field',
            field=models.ImageField(default='static/images/course_logo.png', height_field='340', upload_to='static/courses_logo/', width_field='240'),
        ),
    ]
