# Generated by Django 3.0.1 on 2020-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0015_auto_20200422_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_field',
            field=models.ImageField(default='static/images/course_logo.png', upload_to='static/courses_logo/'),
        ),
    ]
