# Generated by Django 3.0.1 on 2020-04-22 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0016_auto_20200422_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
