# Generated by Django 3.0.1 on 2020-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0019_auto_20200422_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='With effort rivaling my ESO Beginner Tutorial, I have embarked on creating a complete and comprehensive beginner tutorial for League of Legends.  If you know any new players looking to get started or if they just need some guidance, direct them here because this will tell them everything they need!', max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='image_field',
            field=models.ImageField(upload_to='courses_logo/'),
        ),
    ]
