# Generated by Django 3.0.1 on 2020-04-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0020_auto_20200422_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_section',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
