# Generated by Django 3.0.1 on 2020-04-24 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('championsDen', '0021_course_section_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('BR1', 'Brazil'), ('EUN1', 'EU Nordic East'), ('EUW1', 'EU West'), ('JP1', 'Japan'), ('KR', 'Korea'), ('LA1', 'Latin America 1'), ('LA2', 'Latin America 2'), ('NA1', 'North America'), ('OC1', 'Oceania'), ('TR1', 'Turkey'), ('RU', 'Russia')], max_length=15)),
                ('date_of_birth', models.DateField()),
                ('profile_pic', models.ImageField(upload_to='tutor_profile_pic/')),
                ('stripe_acc_id', models.CharField(max_length=100)),
                ('summoner_name', models.CharField(max_length=100)),
                ('rank', models.CharField(max_length=100)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
