# Generated by Django 3.0.1 on 2020-04-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0024_auto_20200424_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_rank',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_icon_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
