# Generated by Django 3.0.1 on 2020-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0025_auto_20200425_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feeback_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
