# Generated by Django 3.0.1 on 2020-04-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0027_auto_20200425_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.CharField(choices=[('Excellent', 'A'), ('Overall Good', 'B'), ('Poor', 'C'), ('Very Poor', 'D'), ('Not Graded', 'NA')], max_length=13, null=True),
        ),
    ]
