# Generated by Django 3.0.1 on 2020-04-25 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0028_auto_20200425_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feeback_url',
            new_name='feedback_url',
        ),
    ]
