# Generated by Django 3.0.1 on 2020-04-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0029_auto_20200425_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='position_played',
            field=models.CharField(choices=[('MID', 'MIDLANE'), ('TOP', 'TOPLANE'), ('JUNGLE', 'JUNGLE'), ('BOT', 'BOTLANE'), ('SUPPORT', 'SUPPORT')], default='SUPPORT', max_length=20),
            preserve_default=False,
        ),
    ]
