# Generated by Django 3.0.1 on 2020-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0030_feedback_position_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_tier',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
