# Generated by Django 3.0.1 on 2020-04-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0031_profile_current_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='position_played',
            field=models.CharField(choices=[('MIDLANE', 'MIDLANE'), ('TOPLANE', 'TOPLANE'), ('JUNGLE', 'JUNGLE'), ('BOTLANE', 'BOTLANE'), ('SUPPORT', 'SUPPORT')], max_length=20),
        ),
    ]
