# Generated by Django 3.0.1 on 2020-04-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0032_auto_20200425_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='grade',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
