# Generated by Django 3.0.1 on 2020-04-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0034_lp_progress_skill_assesment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(blank=True, default='', max_length=5000),
            preserve_default=False,
        ),
    ]
