# Generated by Django 3.0.1 on 2020-04-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0035_auto_20200427_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Global_Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=150)),
                ('gold_per_min', models.FloatField(null=True)),
                ('total_dmg_healed', models.FloatField(null=True)),
                ('CC_applied', models.FloatField(null=True)),
                ('dmg_per_min', models.FloatField(null=True)),
                ('vis_per_min', models.FloatField(null=True)),
                ('kda', models.FloatField(null=True)),
            ],
        ),
    ]
