# Generated by Django 3.0.1 on 2020-04-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0036_global_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='global_stats',
            old_name='gold_per_min',
            new_name='cs_per_min',
        ),
    ]
