# Generated by Django 3.0.1 on 2020-05-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0037_auto_20200430_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skill_assesment_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='suggested_path',
            field=models.ManyToManyField(blank=True, to='championsDen.Course'),
        ),
    ]
