# Generated by Django 3.0.1 on 2020-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('championsDen', '0038_auto_20200501_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
